//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class webt2289_StudentManager_ThuyEntities6 : DbContext
    {
        public webt2289_StudentManager_ThuyEntities6()
            : base("name=webt2289_StudentManager_ThuyEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<University> Universities { get; set; }
    
        public virtual int USP_PRINT_STUDENT(string s_id, string s_name)
        {
            var s_idParameter = s_id != null ?
                new ObjectParameter("S_id", s_id) :
                new ObjectParameter("S_id", typeof(string));
    
            var s_nameParameter = s_name != null ?
                new ObjectParameter("S_name", s_name) :
                new ObjectParameter("S_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_PRINT_STUDENT", s_idParameter, s_nameParameter);
        }
    
        public virtual int USP_PRINT_STUDENT_FULL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_PRINT_STUDENT_FULL");
        }
    }
}
