//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_NET_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string S_id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual Class Class1 { get; set; }
    }
}
